{{- if and .Values.pdb.enabled (or (and .Values.autoscaling.enabled (gt (int .Values.autoscaling.minReplicas) 1)) (and (not .Values.autoscaling.enabled) (gt (int .Values.replicaCount) 1))) -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tails-server.fullname" . }}
  labels:
    {{- include "tails-server.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "tails-server.selectorLabels" . | nindent 6 }}
{{- end }}
