FROM bcgovimages/von-image:next-1

ADD requirements.txt .
ADD requirements.dev.txt .

RUN pip3 install --no-cache-dir -r requirements.txt -r requirements.dev.txt

ADD test ./

ENTRYPOINT ["python", "integration.py"]
