#!/bin/bash
export MSYS_NO_PATHCONV=1
export DOCKERHOST=${APPLICATION_URL-$(docker run --rm --net=host eclipse/che-ip)}
set -e

SCRIPT_HOME="$(cd "$(dirname "$0")" && pwd)"

# =================================================================================================================
# Usage:
# -----------------------------------------------------------------------------------------------------------------
usage() {
  cat <<-EOF
      Usage: $0 [command] [options]
      Commands:
      start - Run tails-server
EOF
  exit 1
}

toLower() {
  echo $(echo ${@} | tr '[:upper:]' '[:lower:]')
}

exportEnvironment() {
  for arg in "$@"; do
    case "$arg" in
      *=*)
        export "${arg}"
        ;;
    esac
  done

  export GENESIS_URL=${GENESIS_URL:-http://$DOCKERHOST:9000/genesis}
  export STORAGE_PATH=${STORAGE_PATH:-/tmp/tails-files}
  export LOG_LEVEL=${LOG_LEVEL:-INFO}
  export TAILS_SERVER_URL=${TAILS_SERVER_URL:-http://$DOCKERHOST:6543}
}

# =================================================================================================================

pushd ${SCRIPT_HOME} >/dev/null
COMMAND=$(toLower ${1})
shift || COMMAND=usage

case "${COMMAND}" in
build)
  docker-compose build
  ;;
start|up)
  exportEnvironment "$@"
  docker-compose up ngrok-tails-server tails-server
  echo "Run './manage logs' for logs" 
  ;;
test)
  exportEnvironment "$@"
  docker-compose up -d ngrok-tails-server tails-server
  docker-compose run tester --genesis-url $GENESIS_URL --tails-server-url $TAILS_SERVER_URL
  # docker-compose down
  ;;
logs)
  docker-compose logs -f
  ;;
down)
  docker-compose down
  ;;
*)
  usage
  ;;
esac

popd >/dev/null