name: Helm Chart Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  # Sometimes chart-releaser might fetch an outdated index.yaml from gh-pages, causing a WAW hazard on the repo
  # This job checks the remote file is up to date with the local one on release
  validate-chart-index:
    name: Validate Chart Index
    permissions:
      contents: read
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: gh-pages
      - name: Download remote index file and check equality
        run: |
          curl -vsSL https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/index.yaml > index.yaml.remote
          LOCAL="$(md5sum < index.yaml)"
          REMOTE="$(md5sum < index.yaml.remote)"
          echo "$LOCAL" = "$REMOTE"
          test "$LOCAL" = "$REMOTE"

  chart-release:
    name: Create and Publish Chart Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'
    needs: [ validate-chart-index ]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Release workload charts
        uses: ./.github/actions/chart_releaser
        with:
          config: .github/actions/chart_releaser/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
